# Generated by Django 6.1.1 on 2026-09-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Fruits & Vegetables', 'Fruits & Vegetables'), ('Dairy & Bakery', 'Dairy & Bakery'), ('Snacks & Packaged Food', 'Snacks & Packaged Food'), ('Beverages', 'Beverages'), ('Household Care', 'Household Care')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imageUrl', models.URLField(blank=True, max_length=500)),
                ('rating', models.FloatField(default=0.0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('availability', models.CharField(choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock')], default='In Stock', max_length=50)),
                ('is_deal', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
